### ISSUE TITLE
Kolizja atomów

### ISSUE THREAD

**Issue by Dawnkai** [Dawnkai/covid#3]
Obecnie atomy przenikają przez siebie i odbijają się jedynie od ścian.
Należy dodać hitbox (preferowane) lub kalkulować (odradzane) odległości od atomów i następne ich odbijanie.
Pomocne linki:
https://stackoverflow.com/questions/27642234/pygame-circle-collision
https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.collide_circle

Kalkulacja kierunku, stopnia i prędkości wedle uznania, według:
https://drive.google.com/drive/folders/1IoM1tIQTbqbW0BJGsf5OCD86Oklc-4ye

**Comment by Cubaster** [comment]
@Dawnkai na chwilę obecną tak wygląda zderzanie się atomów, jeszcze będziemy testować różne przypadki, ale jak dotąd nie widziałem błędów.
