### ISSUE TITLE
Zarażanie atomów

### ISSUE THREAD

**Issue by Dawnkai** [Dawnkai/covid#4]
Obecnie w grze są tylko niebieskie atomy. Należy dodać zarażony atom i sprawić, że po zderzeniu z innym atomem dany atom stanie się zarażony. Można wykorzystać mechanikę kolizji w [poprzednim issue](https://github.com/Dawnkai/covid/issues/3).

Przy projektowaniu należy pamiętać, że symulacja musi się kiedyś skończyć a nie trwać w nieskończoność.

**Comment by Cubaster** [comment]
Temat został już ruszony. Pomysł jest taki że są 3 kolory. Niebieski - zdrowy, fiolet - nosiciel, czerwony - zarażony/zarażający. Przerwa w programie następuje gdy:  wszystkie kulki zdrowe staja się nosicielami, lub gdy zostanie przekroczona pewna liczba ticków w pętli głównej programu - dalej prowadzimy research jaką wartość ustalić. Co do kulki czerwonej to imo współdzielenia wielu parametrów z niebieskimi, wprowadzona będzie jako osobna klasa. Co sądzicie @Dawnkai , @DiWorg ?

**Comment by Dawnkai** [comment]
> 
> 
> Temat został już ruszony. Pomysł jest taki że są 3 kolory. Niebieski - zdrowy, fiolet - nosiciel, czerwony - zarażony/zarażający. Przerwa w programie następuje gdy: wszystkie kulki zdrowe staja się nosicielami, lub gdy zostanie przekroczona pewna liczba ticków w pętli głównej programu - dalej prowadzimy research jaką wartość ustalić. Co do kulki czerwonej to imo współdzielenia wielu parametrów z niebieskimi, wprowadzona będzie jako osobna klasa. Co sądzicie @Dawnkai , @DiWorg ?

2 kolory wystarczą. Zarażony atom to zarażony atom - nie ma podziału na "nosicieli" i "zarażonych" gdyż każdy zarażony jest nosicielem. Nie ma sensu komplikować zadania. Co do wartości to wyjdzie ona najpewniej w praniu gdy już skończycie symulację i zobaczycie dla jakich wartości wynik staje się zbyt rozmyty.

**Comment by jchabora20** [comment]
Popieram przedmówcę, nie ma większej potrzeby, żeby robić podziały na klasy czerwonych/niebieskich.

**Comment by Cubaster** [comment]
Pomysł na 3 grupę która de facto jest grupą niebieskich tylko podczas zderzenia zmieniamy kolor i id kulki.  Bo jak rozumiem z poleceń II.1.d i II.1.h [w materiałach](https://drive.google.com/drive/folders/1IoM1tIQTbqbW0BJGsf5OCD86Oklc-4ye)  to atom czerwony ma być tylko i wyłącznie jeden dlatego pomysł rozróżnienia wizualnego z tych z którymi atom czerwony się już zderzył.

**Comment by Dawnkai** [comment]
Dobry pomysł. Ale możemy nad nim pomyśleć dopiero kiedy symulacja będzie ukończona. Jak na razie trzymaj się dwóch kolorów.

**Comment by Cubaster** [comment]
> Popieram przedmówcę, nie ma większej potrzeby, żeby robić podziały na klasy czerwonych/niebieskich.
co do klasy czerwony uważam ze watro zrobić osobna klasę dla czerwonego bo jego parametry startowe są w wiekszości określone przez treść zadania

**Comment by Dawnkai** [comment]
Nie, żadnych nowych klas. Po to jest klasa, że możesz edytować jej parametry. Dodaj obiekt klasy Atom i zmień mu wartości i problem zniknie.
