### ISSUE TITLE
Skalowanie okna i atomów

### ISSUE THREAD

**Issue by Dawnkai** [Dawnkai/covid#5]
Jeżeli ilość atomów * promień przekroczy rozmiar okna, symulacja się nie powiedzie. Należy skalować okno lub atomy tak, aby wyniki symulacji pozostawały takie same, lecz by były widoczne i zrozumiałe (a nie cały ekran zapełniony atomami).

**Comment by Cubaster** [comment]
W nowym branchu Skala w pliku main została dodane skalowanie atomów. Przeliczanie promienia i prędkości. Na skalowanie okna, o ile wgl to robimy skoro w settings mamy ustawione stałe rozmiary, nie mam pomysłu. Ograniczono liczbę atomów mod 101 + 1 za względu na performance aplikacji.
